knp_snappy:
    pdf:
        enabled:    true
        binary:     '"F:\Global Dependency\wkhtmltopdf\bin\wkhtmltopdf.exe"'
        options:    
            enable-local-file-access: true
    image:
        enabled:    true
        binary:     '"F:\Global Dependency\wkhtmltopdf\bin\wkhtmltoimage.exe"'
        options:    
            enable-local-file-access: true
