security:
    role_hierarchy:
        ROLE_ADMIN: [ROLE_RH, ROLE_USER]
        ROLE_RH: [ROLE_USER]
        ROLE_CANDIDAT: [ROLE_USER]
        ROLE_EMPLOYEE: [ROLE_USER]

    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        App\Entity\Utilisateur: 'auto'
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_utilisateur_email_provider:
            entity:
                class: App\Entity\Utilisateur
                property: Email
        app_utilisateur_username_provider:
            entity:
                class: App\Entity\Utilisateur
                property: Nom_Utilisateur
        app_chain_provider:
            chain:
                providers: ['app_utilisateur_email_provider', 'app_utilisateur_username_provider']
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_chain_provider
            custom_authenticator: App\Security\LoginFormAuthenticator
            entry_point: App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/logout, roles: PUBLIC_ACCESS }
        - { path: ^/admin/community, roles: ROLE_RH }
        - { path: ^/admin, roles: ROLE_RH }
        - { path: ^/rh, roles: ROLE_RH }
        - { path: ^/dashboard, roles: ROLE_USER }
        - { path: ^/offres, roles: ROLE_USER }
        - { path: ^/formations, roles: ROLE_EMPLOYEE }
        - { path: ^/mes-participations, roles: ROLE_EMPLOYEE }
        - { path: ^/communaute, roles: ROLE_EMPLOYEE }
        - { path: ^/users, roles: ROLE_RH }

when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
